### ISSUE TITLE
The video is no longer available

### ISSUE THREAD

**Issue by 3for** [supertestnet/bitvm-workshop#1]
Hi, the video [https://www.youtube.com/watch?v=uurULEZr4PA](https://www.youtube.com/watch?v=uurULEZr4PA) mentioned in README is no longer available now.

**Comment by supertestnet** [comment]
> Hi, the video https://www.youtube.com/watch?v=uurULEZr4PA mentioned in README is no longer available now.

Oops, thanks, fixed! Here is the updated link: https://www.youtube.com/watch?v=LwH9fhY4uGA
